apiName = "Test API"

#Target API under test
targetHost = "localhost"
targetPort = "8282"

#Allowed vairance as a percentage over base values
allowablePeakMemoryVariance = 15.0
allowableServiceResponseTimeVariance = 15.0

#The number of time each test case is executed
numIterations = 1000

#Output locations for generated files
baseStatsOutputDir = "./envStats"
reportOutputDir = "./report"

#Concurrent users per service test
concurrentUsers = 1

#optional template file location
#reportTemplateFile = "."